### ISSUE TITLE
How to do different dependencies based on platform

### ISSUE THREAD

**Issue by aaron-hardin** [jamesmontemagno/AllExtensions-DI-IoC#1]
I really love the idea of using Generic Host with Xamarin, I'm curious how you would go about setting different dependencies based on the platform?

My first attempt was to create IDependencyProvider with a ConfigureServices method and pass an instance of IDependencyProvider into the App constructor, but this feels a little hacky to me.

**Comment by jamesmontemagno** [comment]
So, i think what you would want is to pass in a configuration for each platform.... let me spec it out.

**Comment by jamesmontemagno** [comment]
Basically what you said is what I did :0 take a look :)
